name: CI

on:
  push:
    tags:
      - '*'

jobs:
  build-linux-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Package
        run: mvn clean package -Ppackage

      - name: Upload Linux
        uses: actions/upload-artifact@v2
        with:
          name: DynamoIt-linux
          path: target/DynamoIt.tar.gz

  build-windows-package:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Package
        run: mvn clean package -Ppackage

      - name: Upload Windows
        uses: actions/upload-artifact@v2
        with:
          name: DynamoIt-windows
          path: target/DynamoIt.tar.gz

  build-macos-package:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Package
        run: mvn clean package -Ppackage

      - name: Upload MacOS
        uses: actions/upload-artifact@v2
        with:
          name: DynamoIt-macos
          path: target/DynamoIt.tar.gz

  build-release:
    runs-on: ubuntu-latest
    needs: [build-linux-package, build-windows-package, build-macos-package]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Download Linux artifact
        uses: actions/download-artifact@v2
        with:
          name: DynamoIt-linux

      - name: Upload Release Asset for Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./DynamoIt.tar.gz
          asset_name: DynamoIt-linux.tar.gz
          asset_content_type: application/gzip

      - name: Download windows artifact
        uses: actions/download-artifact@v2
        with:
          name: DynamoIt-windows

      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload Release Asset for Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./DynamoIt.tar.gz
          asset_name: DynamoIt-windows.tar.gz
          asset_content_type: application/gzip

      - name: Download macos artifact
        uses: actions/download-artifact@v2
        with:
          name: DynamoIt-macos

      - name: Upload Release Asset for Macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./DynamoIt.tar.gz
          asset_name: DynamoIt-macos.tar.gz
          asset_content_type: application/gzip
